[profile.default]
src = 'src'
out = 'out'
libs = ['lib']


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainId=1", chainId = 1}
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/v2/api?chainId=1", chainId = 1}